USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE DATABASE DEMO_DB;
CREATE OR REPLACE SCHEMA DEMO_DB.BASE_SCHEMA;

CREATE ROLE IF NOT EXISTS DEMO_ROLE
    COMMENT = 'admin for DEMO_DB';

CREATE USER IF NOT EXISTS DEMO_SERVICE
    PASSWORD = '☺☺☺☺☺☺☺☺☺☺☺☺' --dummified
    MUST_CHANGE_PASSWORD = false;

CREATE OR REPLACE WAREHOUSE demo_db_wh
    WAREHOUSE_SIZE = 'xsmall'
    WAREHOUSE_TYPE = 'standard'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
COMMENT = 'default warehose for demo_db';

USE ROLE SECURITYADMIN;
GRANT ROLE DEMO_ROLE TO ROLE SYSADMIN;
GRANT ROLE DEMO_ROLE TO USER DEMO_SERVICE;

GRANT USAGE ON DATABASE DEMO_DB TO ROLE DEMO_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE DEMO_DB TO ROLE DEMO_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA DEMO_DB.BASE_SCHEMA TO ROLE DEMO_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA DEMO_DB.BASE_SCHEMA TO ROLE DEMO_ROLE;
GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA DEMO_DB.BASE_SCHEMA TO ROLE DEMO_ROLE;
GRANT ALL ON FUTURE PROCEDURES IN SCHEMA DEMO_DB.BASE_SCHEMA TO ROLE DEMO_ROLE;

GRANT ALL ON WAREHOUSE demo_db_wh TO ROLE sysadmin;
GRANT OWNERSHIP ON WAREHOUSE demo_db_wh TO ROLE DEMO_ROLE REVOKE CURRENT GRANTS;
GRANT ALL ON WAREHOUSE demo_db_wh TO ROLE DEMO_ROLE;
